/* This file is generated by **scripts/generate-themes.ts**. Do not modify by hand.  */
import "../themes/dark.css";
import "../themes/light.css";

export const Themes = ["custom", "dark", "light"] as const;
export type Theme = (typeof Themes)[number];
export const defaultTheme: Theme = "dark";
