/* This file is generated by **scripts/generate-code.ts**. Do not modify by hand.  */
import { browserName } from "./platform";
export const PLUGIN_LIST = [
	{
		id: "tabs",
		permissions: ["tabs"],
		prefix: "t",
		name: "Tabs",
		description: "Search browser tabs.",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/tabs.js",
	},
	{
		id: "session-devices",
		permissions: ["sessions"],
		prefix: "sd",
		name: "Session Devices",
		description: "Search your session devices.",
		supportedBrowsers: ["chrome", "chromium", "edg"],
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/session-devices.js",
	},
	{
		id: "prefixes",
		prefix: "?",
		name: "Prefixes",
		description: "Filter for a specific ResultGroup only.",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/prefixes.js",
	},
	{
		id: "tab-groups",
		permissions: ["tabGroups"],
		prefix: "tg",
		name: "Tab Groups",
		description: "List tab groups.",
		supportedBrowsers: ["chrome", "chromium", "edg"],
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/tab-groups.js",
	},
	{
		id: "google",
		prefix: "g",
		name: "Google",
		description: "Google search & Google filters like intitle:youtube.",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/google.js",
	},
	{
		id: "focus-active-input",
		name: "Focus Input",
		providesTheme: false,
		providesResults: false,
		providesConfig: false,
		file: "/plugins/focus-active-input.js",
	},
	{
		id: "management",
		permissions: ["management"],
		prefix: "e",
		name: "Management",
		description: "Search & interact with installed extensions.",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/management.js",
	},
	{
		id: "on-blur-close-window",
		name: "On blur close bob window",
		providesTheme: false,
		providesResults: false,
		providesConfig: false,
		file: "/plugins/on-blur-close-window.js",
	},
	{
		id: "bob-dark-theme",
		name: "Bob dark theme",
		providesTheme: true,
		providesResults: false,
		providesConfig: false,
		file: "/plugins/bob-dark-theme.js",
	},
	{
		id: "content-settings",
		permissions: ["contentSettings"],
		prefix: "cs",
		name: "Content Settings",
		description:
			"Settings that control whether websites can use features such as cookies, JavaScript, and plugins",
		supportedBrowsers: ["chrome", "chromium", "edg"],
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/content-settings.js",
	},
	{
		id: "sessions",
		permissions: ["sessions"],
		prefix: "s",
		name: "Sessions",
		description: "List your recently closed sessions.",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/sessions.js",
	},
	{
		id: "bookmarks",
		permissions: ["bookmarks"],
		prefix: "b",
		name: "Bookmarks",
		description: "Search & interact with bookmarks.",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/bookmarks.js",
	},
	{
		id: "system-storage",
		permissions: ["system.storage"],
		prefix: "sto",
		name: "System Storage",
		description: "Information about your system storage.",
		supportedBrowsers: ["chromium", "chrome", "edg"],
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/system-storage.js",
	},
	{
		id: "window",
		prefix: "win",
		name: "Window",
		description:
			"Interact with chrome windows, for instance 'close other windows'",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/window.js",
	},
	{
		id: "history",
		permissions: ["history"],
		prefix: "h",
		name: "History",
		description: "Search & interact with browser history.",
		providesTheme: false,
		providesResults: true,
		providesConfig: true,
		file: "/plugins/history.js",
	},
	{
		id: "shortcuts",
		prefix: "sc",
		name: "Shortcuts",
		description: "Search for browser shortcuts.",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/shortcuts.js",
	},
	{
		id: "tab-and-group-actions",
		permissions: ["tabs", "tabGroups"],
		prefix: "tga",
		name: "Tab Group Actions",
		description:
			"Combined actions for tabs & groups, for instance group tabs by domain",
		supportedBrowsers: ["chrome", "chromium", "edg"],
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/tab-and-group-actions.js",
	},
	{
		id: "bob-light-theme",
		name: "Bob light theme",
		providesTheme: true,
		providesResults: false,
		providesConfig: false,
		file: "/plugins/bob-light-theme.js",
	},
	{
		id: "bob-results",
		prefix: "bob",
		name: "Bob",
		description:
			"Internal Bob commands like open settings, reset settings ...",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/bob-results.js",
	},
	{
		id: "commands",
		prefix: "c",
		name: "Commands",
		description: "Available commands from extensions.",
		supportedBrowsers: ["chrome", "chromium", "edg"],
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/commands.js",
	},
	{
		id: "clear-search-on-focus",
		name: "Clear search on window focus",
		providesTheme: false,
		providesResults: false,
		providesConfig: false,
		file: "/plugins/clear-search-on-focus.js",
	},
	{
		id: "chatgpt",
		prefix: "gpt",
		name: "ChatGPT",
		description: "Start a chat with chatgpt",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/chatgpt.js",
	},
	{
		id: "top-sites",
		permissions: ["topSites"],
		prefix: "top",
		name: "Top Sites",
		description:
			"The top sites (i.e. most visited sites) that are displayed on the new tab page",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/top-sites.js",
	},
	{
		id: "system-cpu",
		permissions: ["system.cpu"],
		prefix: "cpu",
		name: "System CPU",
		description: "Information about your system CPU.",
		supportedBrowsers: ["chromium", "chrome", "edg"],
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/system-cpu.js",
	},
	{
		id: "downloads",
		permissions: ["downloads"],
		prefix: "d",
		name: "Downloads",
		description: "List and manage downloads.",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/downloads.js",
	},
	{
		id: "system-memory",
		permissions: ["system.memory"],
		prefix: "mem",
		name: "System Memory",
		description: "Information about your system memory.",
		supportedBrowsers: ["chromium", "chrome", "edg"],
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/system-memory.js",
	},
	{
		id: "google-new",
		prefix: "gn",
		name: "Google New",
		description: "Create new google docs, sheets, slides ...",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/google-new.js",
	},
	{
		id: "tab-actions",
		permissions: ["tabs"],
		prefix: "a",
		name: "Tab Actions",
		description: "Interact with browser tabs. Sort, merge, duplicate...",
		providesTheme: false,
		providesResults: true,
		providesConfig: false,
		file: "/plugins/tab-actions.js",
	},
] as BobPluginMeta[];
export const PLUGIN_LIST_SUPPORTED = (() => {
	return PLUGIN_LIST.filter((plugin) => {
		return plugin.supportedBrowsers
			? plugin.supportedBrowsers?.includes(browserName)
			: true;
	});
})();

export const PLUGIN_LIST_THEMES = (() => {
	return PLUGIN_LIST_SUPPORTED.filter((plugin) => {
		return plugin.providesTheme;
	});
})();

export const PLUGIN_LIST_RESULTS = (() => {
	return PLUGIN_LIST_SUPPORTED.filter((plugin) => {
		return plugin.providesResults;
	});
})();

export const PLUGIN_LIST_CONFIGS = (() => {
	return PLUGIN_LIST_SUPPORTED.filter((plugin) => {
		return plugin.providesConfig;
	});
})();

export type BobPluginMeta = {
	id: string;
	name: string;
	file: string;
	prefix?: string;
	permissions?: string[];
	hostPermissions?: string[];
	description?: string;
	supportedBrowsers?: string[];
	providesTheme: boolean;
	providesResults: boolean;
	providesConfig: boolean;
};
