name: on_pr
permissions:
    contents: read
    pull-requests: write
on:
    pull_request:
        branches:
            - main
jobs:
    lint:
        name: lint
        timeout-minutes: 2
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun i
            - run: bun run lint
