name: on_tag
on:
  push:
    tags:        
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Build
        run: |
          bun i
          bun run build
          bun run build:website
          zip -r ./dist/chrome.zip ./dist/chrome
          zip -r ./dist/firefox.zip ./dist/firefox
      - name: Release
        run: |
          git config --global user.email "148579276+otis11@users.noreply.github.com"
          git config --global user.name "on_tag_yml_release"

          gh release create "$GITHUB_REF_NAME" --title "$GITHUB_REF_NAME" ./dist/*.zip

          git checkout main
          git pull
          rm -rf ./website-dist
          mv ./dist/website ./website-dist

          git add website-dist
          git commit -m "$GITHUB_REF_NAME: website-dist update from on_tag.yml"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}