name: publish_website

on:
  workflow_dispatch:

jobs:
  publish_website:
    name: publish_website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Build
        run: |
          bun i
          bun run build:website
      - name: Release
        run: |
          git config --global user.email "148579276+otis11@users.noreply.github.com"
          git config --global user.name "publish_website.yml"

          git fetch --all
          git checkout main
          git pull
          rm -rf ./docs
          mv ./dist/website ./docs

          git add docs
          git commit -m "publish_website.yml: update website."
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
